#!/bin/sh
DIALOG=${DIALOG=dialog}
tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

$DIALOG --clear --title "Auto Function Checksheet System" \
        --menu "\nTry to run AFCS with dialog instead of elaborate GUIs\n" \
        20 80 10 \
  'AFCS.bin' 'Auto Function Checksheet system' \
   2> $tempfile

retval=$?

choice=`cat $tempfile`

case $retval in
  0)
    cd /home/pi/OpenCV/AFCS/bin
    /home/pi/OpenCV/AFCS/bin/$choice
    echo Press RETURN to continue...
    read dummy
    exec $0;;
  1)
    echo "Cancel pressed.";;
  255)
    echo "ESC pressed.";;
esac
